// <auto-generated/>
#pragma warning disable CS0618
using KiotaOpenAIClient.Client.MqttConfig.App.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KiotaOpenAIClient.Client.MqttConfig.App
{
    /// <summary>
    /// Builds and executes requests for operations under \MqttConfig\app
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaOpenAIClient.Client.MqttConfig.app.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KiotaOpenAIClient.Client.MqttConfig.App.Item.WithGuItemRequestBuilder"/></returns>
        public global::KiotaOpenAIClient.Client.MqttConfig.App.Item.WithGuItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("guid", position);
                return new global::KiotaOpenAIClient.Client.MqttConfig.App.Item.WithGuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the KiotaOpenAIClient.Client.MqttConfig.app.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KiotaOpenAIClient.Client.MqttConfig.App.Item.WithGuItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::KiotaOpenAIClient.Client.MqttConfig.App.Item.WithGuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("guid", position);
                return new global::KiotaOpenAIClient.Client.MqttConfig.App.Item.WithGuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaOpenAIClient.Client.MqttConfig.App.AppRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/MqttConfig/app", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KiotaOpenAIClient.Client.MqttConfig.App.AppRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/MqttConfig/app", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
